@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.oilmod.oilforge;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;

//todo make autogenerated